-- schema.sql
DROP TABLE IF EXISTS app_logs;
CREATE TABLE IF NOT EXISTS app_logs (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                        level VARCHAR(16) NOT NULL,
    service VARCHAR(128),
    host VARCHAR(128),
    thread VARCHAR(128),
    request_id VARCHAR(64),
    user_id VARCHAR(64),
    logger VARCHAR(256),
    exception_type VARCHAR(256),
    message CLOB NOT NULL,
    stack_trace CLOB,
    context CLOB,
    resolved BOOLEAN DEFAULT FALSE,
    tags VARCHAR(256)
    );
CREATE UNIQUE INDEX IF NOT EXISTS idx_app_logs_request_id ON app_logs(request_id);
